### ISSUE TITLE
make it optional?

### ISSUE THREAD

**Issue by Agarian** [AJS-development/verse#1]
i have a suggestion. making a config for this...
*updatemsg*
you would set it to 1 to activate it. 0 for deactivated. it should be activated by default tho
and yes i've been quite active with suggestions...apologies if your email gets filled up with these. 
you're not the only one it happens to =\

**Comment by Andrews54757** [comment]
I am going to make it optional but it will be in the next update though

**Comment by Andrews54757** [comment]
I made it optional agarian
